complexity:
  LongMethod:
    threshold: 100
    ignoreAnnotated: [ 'Composable' ]
  CyclomaticComplexMethod:
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  ComplexCondition:
    threshold: 7

performance:
  SpreadOperator:
    active: false

formatting:
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
  ImportOrdering:
    active: false
  MaximumLineLength:
    active: false
  MultiLineIfElse:
    active: false
  Indentation:
    indentSize: 2
  PropertyWrapping:
    active: false
  ParameterWrapping:
    active: false
  ParameterListWrapping:
    active: false
  ArgumentListWrapping:
    indentSize: 2
    maxLineLength: 150
  KdocWrapping:
    active: true
    indentSize: 2
  Wrapping:
    indentSize: 2
    active: false
  CommentWrapping:
    active: false
  Filename:
    active: false
  PackageName:
    active: false
  AnnotationOnSeparateLine:
    active: false

style:
  MagicNumber:
    active: false
    ignoreAnnotated: [ 'AllowMagicNumber' ]
  ForbiddenComment:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  ThrowsCount:
    active: false
  ReturnCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  MaxLineLength:
    active: false

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  MatchingDeclarationName:
    active: false
  VariableNaming:
    active: false
  PackageNaming:
    packagePattern: '[a-z]+(\._?[_?A-Za-z0-9]*)*'
