site_name: 'ComposeInvestigator'
site_url: 'https://jisungbin.github.io/ComposeInvestigator'
site_description: 'Trace the recomposition of a Composable with its cause without any boilerplate code'
site_author: 'Ji Sungbin'

repo_name: 'ComposeInvestigator'
repo_url: 'https://github.com/jisungbin/ComposeInvestigator'

edit_uri: edit/main/documentation/docs/
copyright: 'ComposeInvestigator ⓒ 2024 Ji Sungbin'

theme:
  name: 'material'
  font:
    text: Noto Sans
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.action.view

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.saneheaders
  - mdx_gh_links:
      user: jisungbin
      repo: ComposeInvestigator

nav:
  - 'Overview': 'index.md'
  - 'Advanced': 'advanced.md'
  - 'Under the Hood': 'internal.md'
  - 'Change Log': 'changelog.md'
  - 'Compiler API ⏏': 'https://jisungbin.github.io/ComposeInvestigator/compiler/api/'
  - 'Runtime API ⏏': 'https://jisungbin.github.io/ComposeInvestigator/runtime/api/'
